### PR TITLE
Updated configuration for BOLT

### PR DESCRIPTION
**Pull request by ChristianKuehnel**
HI @metaflow ,

I created an initial configuration based on the discussion around supporting BOLT in #364. Can you please take a look if that covers all the changes we need?

Re-deploying the Debian docker image (with the additional library) is optional. 

Thx,
Christian

### CODE REVIEW

**Comment by metaflow** [comment]
I will try to rebuild docker with an updated image.
Note that at the moment we will NOT be running bolt checks. I will add this separately.

**Comment by malharjajoo** [comment]
I'm not sure but I think this may be causing an error when submitting patches on Phabricator ?

Im getting an error:
https://buildkite.com/llvm-project/premerge-checks/builds/70409#acbd9cab-3a33-42bd-9e24-aeb485181552


```
CMake Error at CMakeLists.txt:76 (MESSAGE):
--
  | bolt isn't a known project:
  | clang;clang-tools-extra;compiler-rt;cross-project-tests;libc;libclc;libcxx;libcxxabi;libunwind;lld;lldb;mlir;openmp;polly;pstl;flang
  |  

```

**Comment by metaflow** [comment]
@malharjajoo Sorry for that, I have not realized that previous patch would cause failures if BOLT has not landed yet. Reverted.

**Comment by ChristianKuehnel** [comment]
Hi @malharjajoo ,

yes, you're right, this patch broke the build as BOLT has not yet landed in the monorepo. It's planned to land end of the week and we were preparing the pre-merge testing already.

I just reverted the patch.

@metaflow 
Can you please re-submit the changes once BOLT has landed?

**Comment by malharjajoo** [comment]
Thank you !

**Pull request merged**
