### PR TITLE
Enable -DLLVM_BUILD_EXAMPLES=ON during pre-merge testing

### PR DESCRIPTION
**Pull request by joker-eph**

### CODE REVIEW

**Comment by ChristianKuehnel** [comment]
From the [CMakeLists.txt](https://github.com/llvm/llvm-project/blob/14b947f306ac7bc2e4eb55ac1e4255fd762b217b/llvm/CMakeLists.txt#L538)
> "Build the LLVM example programs. If OFF, just generate build targets." 

@joker-eph 
Do you have an impression on how big the impact on build times is?

**Comment by metaflow** [comment]
@joker-eph Hi Mehdi! I have started https://buildkite.com/llvm-project/llvm-master-build/builds/220 to check if it affects speed significantly. Could you please give some context for this flag? The documentation for it is quite.. short.

**Comment by joker-eph** [comment]
This flag enables building the "examples": https://github.com/llvm/llvm-project/tree/master/llvm/examples
(or https://github.com/llvm/llvm-project/tree/master/mlir/examples )

The examples are usually fairly small and contained, but many of these also correspond to the docs/tutorials here: https://llvm.org/docs/tutorial/index.html (or https://mlir.llvm.org/docs/Tutorials/Toy/Ch-1/ )

**Comment by echristo** [comment]
This should be negligible impact on build times and is a really good idea.

**Pull request merged**
