### PR TITLE
Add libc to Pre-merge checks

### PR DESCRIPTION
**Pull request by abrachet**

### CODE REVIEW

**Comment by abrachet** [comment]
@googlebot I signed it!

**Comment by ChristianKuehnel** [comment]
I'm a bit hesitant right now to add projects as I would like the pre-merge tests to be fast, see also the discussion in #53 and #55.  Do you have an estimate on build and test times for libc?

**Comment by abrachet** [comment]
The build times are very short, it is quite small. No worries if you want to keep it out though, it's not a huge deal just a nice to have :)

I've done some benchmarks for reference, I've use -j32 to try to get as close to n1-standard-32 as possible.

This is with re-linking all test files and running them:
`/usr/bin/time -p ninja check-libc -j32`
...
```
real 2.74
user 3.06
sys 0.72
```

To build with no projects specified, ninja says there are 2789 jobs:
`rm -rf * && cmake ../llvm -GNinja && /usr/bin/time -p ninja -j32`
```
real 623.09 # 10.3833 seconds
user 11835.10
sys 1158.86
```
I messed up and used my shells time here, sorry about the different formats
When building with libc, there are 2832 jobs:
`rm -rf * && cmake ../llvm -GNinja -DLLVM_ENABLE_PROJECTS=libc && time -p ninja -j32`
```
Executed in  611.96 secs   fish           external  
   usr time  195.87 mins  273.00 micros  195.87 mins 
   sys time   18.96 mins  354.00 micros   18.96 mins
```

So libc is small enough that it makes effectively no difference.

**Comment by ChristianKuehnel** [comment]
Thx for the analysis. Let's give it a shot

**Pull request merged**
